Cost center client side
third-culture-software/bhima pull request #1105
Opened 2017-01-19 14:23 UTC by DedrickEnc

This PR is implementing a client side of a cost center module and it is highly dependent to to #1080 .
He are tasks to perform : 

- [x] User Interface implementation

- [ ] Testing 

Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [ ] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [ ] Run integration tests.
 - [ ] Run end-to-end tests.
 - [ ] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

2017-01-23 22:00 UTC, DedrickEnc commented
@sfount

2017-02-01 13:44 UTC, DedrickEnc commented
Now the grid has a new column for showing the fee center value like this : 

![value in grid](https://cloud.githubusercontent.com/assets/5418919/22509099/e5ffbcf0-e88c-11e6-94d1-23a6a0e36475.PNG)

2017-02-01 14:38 UTC, jniles requested changes
@DedrickEnc, these are a lot of changes that represent a lot of work.

Many of the changes are based on old code that don't abide by best practices.  In general, good practices to follow are:
 1. Always pass parameters to the database by escaping them to prevent SQL injection attacks.  MySQL also handles translation of JS's BLOB --> BINARY, new DATE() ---> DATETIME, and other nice features.  You should always compose your SQL with `?` question mark syntax and pass the parameters as an array to `db.exec()`.
 2. Using tested libraries is almost always better than writing your own.  This applies to the `PrototypeApiService` which has Karma testes written for it, and `FormUtils`, which is used in almost every set of `e2e` tests in the application.
 3. Always use the `translate` directive where possible.
 4. Try to move HTML templates out of Javascript.  They cannot be cached efficiently and only cause the browser to more work.

Once these changes are made, the code will be much easier to audit for correctness.

2017-02-01 14:38 UTC, jniles commented on client/src/i18n/en.json
> +    "CREATE"        : "Create",
Can this just be `FORM.LABELS.CREATE`?

2017-02-01 14:38 UTC, jniles commented on client/src/i18n/en.json
> +    "UPDATE"        : "Update",
Can this just be `FORM.LABELS.UPDATE`?

2017-02-01 14:38 UTC, jniles commented on client/src/js/services/FeeCenterService.js
> +function FeeCenterService($http, util, translate) {
I think you can reduce this entire service to the following lines:

```js
function FeeCenterService(PrototypeApiService, $translate) {
  var service = new PrototypeApiService('/fee_centers');

  service.fullRead = function fullRead(id) {
    return this.read(id, { full : 1 });
  };

  service.formatRecord = function formatRecord(list) {
    list.forEach(function (item) {
      item.type = item.is_cost === 1 ? translate.instant('FEE_CENTER.COST_CENTER') : translate.instant('FEE_CENTER.PROFIT_CENTER');
      item.principalState = item.is_principal === 1 ? translate.instant('FORM.LABELS.YES') : translate.instant('FORM.LABELS.NO');
    });
    return list;
   }

  return service;
}
```
Doing this would help with maintainability/testing, reduce the size of the JS shipped to the client, and reduce the amount of time Chrome spends parsing the JS.

2017-02-01 14:38 UTC, jniles commented on client/src/js/services/FeeCenterService.js
> +  function fullRead (id){
I highly recommend that you just use the standard `read()` method, passing the optional parameter as a JSON object.

2017-02-01 14:38 UTC, jniles commented on client/src/js/services/FinancialService.js
> +     var url = '/fee_centers?is_cost=1';
This is old code so it's not a necessary fix, but you could also just extend the `params` with `{ is_cost: 1}`.  Like this:

```js
var baseUrl = '/fee_centers';

function readCenter(id, params) {
  return $http.get(baseUrl, { params : params })
    .then(util.unwrapHttpResponse);
}

function readProfitCenter(id, params) {
  var profitParameters = angular.extend(params, { is_cost : 0 });
  return readCenter(id, profitParameters);
}

function readCostCenter(id, params) {
  var costParameters = angular.extend(params, { is_cost: 1 });
  return readCenter(id, costParameters);
}
```

2017-02-01 14:38 UTC, jniles commented on client/src/partials/fee_center/feeCenter.modal.html
> +        {{ "FEE_CENTER.ADDING_FEE_CENTER" | translate }}
These should all use the `translate` directive to reduce `$$watchers`.

[From the documentation](https://angular-translate.github.io/docs/#/guide/05_using-translate-directive)
>  Using translate filter is great, but using translate directive is better. It turned out that having too many filters in a view sets up too many watch expressions, which is why angular-translate also provides a directive to translate your contents in view layer.

2017-02-01 14:38 UTC, jniles commented on client/src/partials/fee_center/feeCenter.modal.html
> +        theme="bootstrap"
Just as a note: the `bootstrap` theme is set globally in `app.js`, there is no need to include it in `ui-select` components.

2017-02-01 14:38 UTC, jniles commented on client/src/partials/fee_center/feeCenter.modal.html
> +      <i class="fa fa-ban"></i> {{ 'FORM.BUTTONS.CANCEL' | translate }}
Most of the other forms/modals in the application do not use icons on the buttons.  It would be best if we picked one style.  If you like icons on buttons, make an issue for discussion and we can standardize our practices.

2017-02-01 14:38 UTC, jniles commented on client/src/partials/fee_center/feeCenter.modal.js
> +    if (!feeCenterForm.$dirty) { return; }
Just so you know, this is equivalent to `if (feeCenterForm.$pristine) { return; }` which is slightly easier to read.  That is why angular gives you both `$dirty` and `$pristine` values.

2017-02-01 14:38 UTC, jniles commented on client/src/partials/fee_center/feeCenter.modal.js
> +    $state.transitionTo('feeCenter.list');
`$state.transitionTo()` is a pretty low-level method of `ui-router`.  [The wiki recommends $state.go() for transitions](http://stackoverflow.com/questions/21105528/difference-between-state-transitionto-and-state-go-in-angularjs).

2017-02-01 14:38 UTC, jniles commented on client/src/partials/fee_center/fee_center.html
> +      <li class="static">{{ "TREE.FINANCE" | translate }}</li>
These should use the `translate` directive.

2017-02-01 14:38 UTC, jniles commented on client/src/partials/fee_center/fee_center.js
> +  var actionTemplate = '<div class="ui-grid-cell-contents">' +
It is best to move these into their own HTML templates.  That way they can be cached, gzipped, and the JS minifier doesn't have to deal with these long strings.

2017-02-01 14:38 UTC, jniles commented on client/src/partials/fee_center/fee_center.js
> +    '<a href="" uib-popover="{{grid.appScope.showNote(row.entity.note)}}" ' +
Why not ...
```html
<a href="" uib-popover="{{row.entity.note}}">
```
?

2017-02-01 14:38 UTC, jniles commented on client/src/partials/templates/grid/feeCenterType.tmpl.html
> +  <span ng-class="{'label label-info': row.entity.is_cost === 1, 'label label-warning': row.entity.is_cost !== 1}">
You could move the `label` class out of this `ng-class` to make it read better.

2017-02-01 14:38 UTC, jniles commented on client/src/partials/templates/grid/fee_center_value.cell.html
> +<div class="ui-grid-cell-contents" title="TOOLTIP" ng-if="row.groupHeader">
These is no need to separate these two out -- you aren't even using `ui-grid-grouping`.

2017-02-01 14:38 UTC, jniles commented on client/src/partials/templates/grid/fee_center_value.cell.html
> +<div class="ui-grid-cell-contents"  title="TOOLTIP" ng-if="!row.groupHeader">
You actually don't need to have a separate template for this. Just amend your gridOptions to be
```js
{ field : 'value', displayName : 'FORM.LABELS.VALUE',
        headerCellFilter: 'translate', 
        cellFilter: 'currency:' + Session.enterprise.currency_id
}
```
Since all you are doing is applying a filter, you can build it right into to `ui-grid` options!

2017-02-01 14:38 UTC, jniles commented on server/controllers/admin/services.js
> +LEFT JOIN (SELECT fee_center.label AS cost_center_name, id FROM fee_center WHERE fee_center.is_cost = 1) AS cc ON s.cc_id = cc.id
Can't you just LEFT JOIN on fee_center as cc?

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/accounts/index.js
> +    LEFT JOIN fee_center AS fc ON a.fc_id = fc.id`;
:+1:

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +* @param {object} req The express request object
At this point, I think that all developers know how expressjs works.  There is no need to document these parameters.

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +* var feeCenters = require('finance/fee_centers');
This file is actually `finance/feeCenter`.

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +  if(req.query.available === '1') {
What does this parameter do?  What is an available fee center?

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +    filter += `fc.is_cost = ${req.query.is_cost} `;
What happens if `req.query.is_cost` is `(DELETE FROM general_ledger WHERE 1); -- ` ?

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +    console.log('******* erreur', err);
This should have proper error handling.

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +  sql = filter === '' ? sql + ordering : sql + 'WHERE ' + filter + ordering;
If you used `db.exec(sql, [params])`, you could write your code so that you didn't have to check if `filter === ''` all the time.

2017-02-01 14:38 UTC, jniles commented on client/src/partials/fee_center/fee_center.js
> +'use strict';
There is no need to `use strict` on the client.  Gulp will insert it for us.

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +  lookupFeeCenter(feeCenterId)
This used to be best practices until we created our `errors/*.js` libraries for error handling.  You can now just do a UPDATE and then throw `NotFound()` if the `affectedRows` is 0 --- less database queries = easier for raspberry pi!

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +      if (rows.length === 0) {
You can use `db.one()` to handle this case automatically.

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +        optionalCondition = ' OR gl.account_id IN (' + rows.join(',') + ')';
It would be much, much better to use `db.exec()`'s parameters instead of doing string concatenation in JS.

2017-02-01 14:38 UTC, jniles commented on server/controllers/finance/generalLedger/index.js
> +    .catch(function (err){console.log(err);});
This should be handled.

2017-02-01 14:38 UTC, jniles commented on server/models/schema.sql
> +  `is_cost` tinyint(1) DEFAULT 0,
Since you do a lot of queries on `is_cost`, as a performance improvement, you could put an INDEX on it.

2017-02-01 14:38 UTC, jniles commented on server/models/schema.sql
> +  `auxi_cc_id` smallint(6) NOT NULL,
What is `auxi_cc_id`?  Can it be removed since we have `auxiliary_cost_id`?

2017-02-01 14:38 UTC, jniles commented on test/end-to-end/fee_center/feeCenter.page.js
> +  const page = this;
:+1:

2017-02-01 14:38 UTC, jniles commented on test/end-to-end/fee_center/feeCenter.page.js
> +  function editFeeCenter(n) {
This is a nice wrapper. :+1:

2017-02-01 14:38 UTC, jniles commented on test/end-to-end/fee_center/feeCenterCU.page.js
> +function CreateUpdateFeeCenterPage() {
Many of these methods are already contained in helper libraries such as `FormUtils`.  Is there a reason to duplicate the effort here?

2017-02-01 14:38 UTC, jniles commented on test/integration/feeCenter.js
> + * @todo - there are some tests missing:
Good comment :+1:

2017-02-01 14:38 UTC, jniles commented on test/integration/feeCenter.js
> +  /* @todo - make this route ?detailed=1 to conform to standards */
Good comment :+1:

2017-02-01 14:38 UTC, jniles commented on test/integration/feeCenter.js
> +    return agent.get('/fee_centers/:id/value'.replace(':id', FETCHABLE_FEE_CENTER_ID))
Since we are using Node v4+, you can just use string substitution:
```js
return agent.get(`/fee_centers/${FETCHABLE_FEE_CENTER_ID}/value`):
```

2017-02-01 14:38 UTC, jniles commented on test/integration/feeCenter.js
> +        expect(res.body.value).to.satisfy(function (value) { return value >= 0;});
This is a nice test :+1:

2017-02-07 15:57 UTC, jniles commented
@DedrickEnc  does the PR supersede https://github.com/IMA-WorldHealth/bhima-2.X/pull/1101?

2017-03-03 13:37 UTC, closed without merging

2017-03-08 10:51 UTC, DedrickEnc commented on test/end-to-end/fee_center/feeCenterCU.page.js
> +function CreateUpdateFeeCenterPage() {
I followed the page object as detailed from the official protractor tutorial, and now my buttons, radio button, and text field are privates members of my page. this let me represent a structure of my page by reading the code I can guess how many element I have on the page and I many actions or methods (interface) the page gives me.

2017-03-08 11:18 UTC, jniles commented on test/end-to-end/fee_center/feeCenterCU.page.js
> +function CreateUpdateFeeCenterPage() {
In my view, the page object methods works best on really complicated pages - such as Complex Vouchers, Patient Invoice, Posting Journal...

Your current page is a simple form - in this case, it triples the amount of code needed to maintain and upgrade with marginal benefit.