Fee center schema and API
third-culture-software/bhima pull request #1156
Opened 2017-02-09 11:20 UTC by DedrickEnc

This PR adds an initial schema and API to continue the feature developing
Here are things to notice in this PR : 

- The table ```cost_center``` and ```profit_center``` are deleted
-  A new table ```fee_center``` is created```
- The modules cost center and profit center are deleted
- The service module is updated to fit with the  changes
- The delete functionality is not yet implemented and the integration  test for this functionality is ignored, because we did not talk about that during the design. 
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

2017-02-09 11:21 UTC, DedrickEnc commented
@jniles

2017-02-09 15:25 UTC, jniles requested changes

2017-02-09 15:25 UTC, jniles commented on server/controllers/finance/feeCenter.js
> +    filter += `fc.is_cost = ${req.query.is_cost} `;
I have pulled your branch typed this into my web browser.
```
http://localhost:8080/fee_centers?is_cost=1 UNION SELECT id, password as label, active AS is_cost FROM user AS fc ; --
```
And this is the result I got:
![sql injection attack](https://cloud.githubusercontent.com/assets/896472/22788931/b6495722-eee1-11e6-8233-4fdab507dfae.png)
_Fig 1: An SQL Injection Attack_

These attacks are quite common across the web.  We have a library called `db` that will parse the parameters and prevent sensitive information like passwords from leaking.

You've made this mistake before and it makes me sad to have this problem across multiple code reviews.

2017-02-10 12:57 UTC, DedrickEnc commented on server/controllers/finance/feeCenter.js
> +    filter += `fc.is_cost = ${req.query.is_cost} `;
I have written an email

2017-03-03 13:37 UTC, closed without merging