refactor(patient registry)
third-culture-software/bhima pull request #1771
Opened 2017-06-07 20:38 UTC by lomamech

refactor(patient registry)  …
- Ingrate grid save state
- Add dropdownfor for Column configuration, Downlowas view as CSV PDF
- Remove bhRenderer Dropdown

Update the standard for reduce technical debt and give required features
- Use the latest FilterService
- Update test E2E

closes #1748

2017-06-08 09:30 UTC, sfount commented
@lomamech I haven't fully reviewed the code here but I've tested this feature. Everything looks good but I have a few comments: 
* The grid overflows on the bottom of the page - it would be best to the `grid-full-height-with-filters` on the grid here. 
* (very minor) the tabs inside of the modal do not take up the full width of the modal. I think the HTML isn't exactly correct. 
* The filters applied to the grid are not applied to the PDF and CSV reports that are generated. I think @DedrickEnc had this issue in his pull request https://github.com/IMA-WorldHealth/bhima-2.X/pull/1768/ . You could ask him how he resolved this.

2017-06-08 09:50 UTC, jniles commented
I'll take a look at the code.

2017-06-08 10:33 UTC, jniles requested changes
@lomamech, there are a few changes to be made before this lands in master.

 1. Make sure that you rename code that you copied from other contexts - in the case `openJournal` shouldn't appear in the patient registration controller.
 2. Make sure you use all the methods you define - I made a few comments on what seems to be extra code.
 3. Make sure you use the `translate` directive instead of the filter for performance reasons.

Your use of the search modal page object was excellent.  Great tests :+1:

2017-06-08 10:33 UTC, jniles commented on client/src/modules/account_statement/account_statement.html
> +                <i class="fa fa-file-pdf-o"></i> <span translate>FORM.BUTTONS.PDF_EXPORT</span>
Nice improvement :+1:

2017-06-08 10:33 UTC, jniles commented on client/src/modules/patients/patients.service.js
> +  var service = new Api(baseUrl);
Cool!  Great refactor :+1:

2017-06-08 10:33 UTC, jniles commented on client/src/modules/patients/patients.service.js
> +  service.download = function download(type) {
You never actually use this method.  Should it be removed?

2017-06-08 10:33 UTC, jniles commented on client/src/modules/patients/registry/registry.js
> +  function onRegisterApi(gridApi) {
It doesn't look like you ever use `onRegisterApi()`.  Do you need it?

2017-06-08 10:33 UTC, jniles commented on client/src/modules/patients/registry/registry.js
> +  vm.openJournalReport = function openJournalReport() {
I don't think this should be called `openJournalReport` since it isn't the journal.  Maybe `PatientReport`?

2017-06-08 10:33 UTC, jniles commented on client/src/modules/patients/registry/search.modal.html
> +          <label class="control-label">
Please use the `translate` directive instead of the `translate` filter.

2017-06-08 10:33 UTC, jniles commented on test/end-to-end/patient/registry.search.js
> +const SearchModal = require('../shared/search.page');
:+1:  Good usage of Search Modal

2017-06-08 18:23 UTC, jniles submitted a review, later dismissed
@lomamech, my other comments look like they have been addressed - well done.

I've caught one more critical bug - the AppCache key needs to change.  It should be unique to the Patients Registry.

After that, code LGTM 👍

2017-06-08 18:23 UTC, jniles commented on client/src/modules/patients/patients.service.js
> +  var filterCache = new AppCache('cash-filters');
Oh - didn't catch this.  This should be `patient-filters` or something.  If you copied this code directly from the Cash Payments Registry, you will find it using Cash's filters.

2017-06-08 18:23 UTC, jniles commented on client/src/modules/patients/registry/registry.html
> +      class="grid-full-height-with-filters"
Great fix :+1:

2017-06-15 14:10 UTC, sfount reviewed
LGTM. There are 1 or 2 comments that should be addressed. I will pull this and check the functionality!

2017-06-15 14:10 UTC, sfount commented on client/src/modules/patients/patients.service.js
> +  var filterCache = new AppCache('cash-filters');
The key here cannot be the same as cash filters - the filters for the cash registry are not all compatible with the patient registry.  This key must change.

2017-06-15 14:10 UTC, sfount commented on client/src/modules/patients/patients.service.js
> +    { key : 'custom_period_start', label : 'PERIODS.START', valueFilter : 'date' },
It would good to add the comparison here so that the filters display 'Period Start > DD/MM/YYYY' and 'Period End < DD/MM/YYY'. 

You can do this by passing in the `comparitor` attribute, for example: 
```js
{ key : 'custom_period_start', label : 'PERIODS.START', valueFilter : 'date', comparitor : '>'}
```

2017-06-15 14:10 UTC, sfount commented on server/controllers/medical/patients/index.js
> +  const filters = new FilterParser(options, { tableAlias : 'p', autoParseStatements : false  });
👍

2017-06-22 12:00 UTC, sfount commented
@lomamech All the comments here have been addressed, great work! 

I've noticed that the export to CSV and PDF features do not work as expected. 

1. Export CSV fails (500 error) 
2. PDF and CSV exports to not have the filters applied.

These should be resolved before this is merged into master.

2017-06-23 10:16 UTC, sfount commented
@lomamech changes applied are excellent, this works very well. One final comment is that the currently selected period should be selected by default when the user opens the search modal - this should only be one line of code to set the default value on initialisation.

2017-07-06 12:24 UTC, merged