feature(Cotisation Management)
third-culture-software/bhima pull request #2303
Opened 2017-11-24 14:54 UTC by lomamech

- Implement API for Cotisation Management
- Implement test Integration for Cotisation Management
- Implement client side for cotisation Management
- Update bhAccountSelect to allow the filter of account by Classe
- Fix error in Account Management Set the property classe in Registred and
  Updated Account
- Implement test E2E for Cotisation Management

reference #2292

2017-11-28 10:25 UTC, jniles requested changes
@lomamech, a few comments here.

I'm pretty sure account `classe` and account type_id are the same thing - especially after the modifications by @mbayopanda which added in Actif and Passif and so on.  Could you use account type_id instead?

Otherwise, the code looks pretty good!

2017-11-28 10:25 UTC, jniles commented on client/src/i18n/en/cotisation.json
> +    "ADD_COTISATION" : "Add a Cotisation",
It looks like cotisation is [membership fee](https://translate.google.com/#auto/en/cotisation) in English.  I would propose calling it an "employment fee" so it doesn't get confused with other types of fees.

2017-11-28 10:25 UTC, jniles commented on client/src/js/components/bhAccountSelect.js
> +    $ctrl.classe = $ctrl.classe || '';
The account class should be the same thing as the account type.  Can you call this account type and use that?

2017-11-28 10:25 UTC, jniles commented on client/src/modules/cotisations/cotisations.routes.js
> +      url : '/:id/edit',
:+1:

2017-11-28 10:25 UTC, jniles commented on server/controllers/finance/accounts/index.js
> +  filters.equals('locked');
Nice!

2017-11-28 10:25 UTC, jniles commented on test/end-to-end/cotisations/cotisations.page.js
> +  errorOnDeleteCotisation(n) {
Can you make this refer to a text instead of an index?  It will make the test much easier to modify in the future.

2017-11-29 12:33 UTC, lomamech commented
@DedrickEnc @jniles

In the optics that must be added, the four account and the six account at the table "rubric", it seems good to me to gather all these different elements in one table, so I want to block all the PR in course (Rubric, Tax and Contribution) and merge them into a single Table payroll rubric

2017-11-29 12:33 UTC, closed without merging