Feature holiday management
third-culture-software/bhima pull request #2326
Opened 2017-12-04 14:47 UTC by lomamech

feature(HolidayManagement)  …
- Implement API for Holiday Management
- Implement Integration test for Holiday Management
- Implement component bhEmployeeSelect
- Impement client side for Holiday Management
- Implement test E2E for Holiday Management
- Prevent to create for an employee holidays periods nested

reference #2292

2017-12-11 14:14 UTC, jniles requested changes
@lomamech  great work porting this!  I couldn't have been easy.  I've made a few clean up suggestions.

2017-12-11 14:14 UTC, jniles commented on .env.development
> +DEBUG=app
:+1:

2017-12-11 14:14 UTC, jniles commented on test/end-to-end/holidays/holidays.page.js
> +  getHolidayCount() {
It doesn't look like you ever use this.  Do you need it?

2017-12-11 14:14 UTC, jniles commented on client/src/i18n/en/form.json
> +            "EMPLOYEE": "Select an Employee",
:+1:

2017-12-11 14:14 UTC, jniles commented on client/src/js/components/bhEmployeeSelect.js
> +    $ctrl.onSelectCallback = $ctrl.onSelectCallback || angular.noop;
Since this is a required binding, it shouldn't ever be null.  There is no need for this code.

2017-12-11 14:14 UTC, jniles commented on client/src/js/components/bhEmployeeSelect.js
> +      });
This should probably include `Notify.handleError` to catch HTTP errors.

2017-12-11 14:14 UTC, jniles commented on client/src/js/components/bhEmployeeSelect.js
> +  $ctrl.onSelect = function ($item, $model) {
There's no need to have `$model` defined here.

2017-12-11 14:14 UTC, jniles commented on client/src/modules/holidays/holidays.js
> +  function createHoliday() {
Can you just use a `ui-sref` instead of defining JavaScript functions?  Both this and edit could benefit from it.

2017-12-11 14:14 UTC, jniles commented on client/src/modules/holidays/holidays.js
> +  'NotifyService', 'uiGridConstants', '$state', 'SessionService',
Do you use `SessionService`?  It doesn't look like it from here.  Could you remove it?

2017-12-11 14:14 UTC, jniles commented on client/src/modules/holidays/holidays.routes.js
> +        holiday : { value : null },
Do you ever use `$state.params.holiday`?   I couldn't find it.  If not, go ahead any remove these from both the edit and create state.

2017-12-11 14:14 UTC, jniles commented on client/src/modules/holidays/holidays.service.js
> + * @extends PrototypeApiService
:+1:

2017-12-11 14:14 UTC, jniles commented on client/src/modules/holidays/modals/holiday.modal.html
> +        validation-trigger="HolidayModalCtrl.$submitted"
I think this should be `HolidayForm.$submitted`.  The controller never has a `$submitted` property set on it.

2017-12-11 14:14 UTC, jniles commented on client/src/modules/templates/bhEmployeeSelect.tmpl.html
> +    ng-class="{ 'has-error' : EmployeeForm.$$parent.$submitted && EmployeeForm.employee_id.$invalid }">
`$$parent` doesn't exist on the form - it should be `$$parentForm`.  [See this answer for more info](https://stackoverflow.com/a/31984524/6251968)

2017-12-11 14:14 UTC, jniles commented on client/src/modules/templates/bhEmployeeSelect.tmpl.html
> +    <div class="help-block" ng-messages="EmployeeForm.employee_id.$error" ng-show="EmployeeForm.$$parent.$submitted">
Same here for `$$parentForm`.

2017-12-11 14:14 UTC, jniles commented on server/controllers/admin/holidays.js
> +        throw new Unauthorized('Holiday Nested.', 'ERRORS.HOLIDAY_NESTED');
I don't think this should be unauthorized (403).  Probably a `BadRequest` error is better (400).

2017-12-11 14:14 UTC, jniles commented on server/controllers/admin/holidays.js
> +        throw new Unauthorized('Holiday Nested.', 'ERRORS.HOLIDAY_NESTED');
Same here - this should be `BadRequest`.  The user inserted bad information

2017-12-11 14:14 UTC, jniles commented on server/controllers/admin/holidays.js
> +        throw new NotFound(`Could not find a Holiday with id ${req.params.id}`);
:+1:

2017-12-11 14:14 UTC, jniles commented on server/controllers/admin/holidays.js
> +      res.status(204).json();
It would be better to use `res.sendStatus(204)` since this response isn't actually JSON.

2017-12-11 14:14 UTC, jniles commented on server/models/bhima.sql
> +  (57,  'Human Ressources','TREE.HUMAN_RESSOURCES','',0,'modules/human_ressources/','/human_ressources/'),
`resources` should only have one `s`.

2017-12-11 14:14 UTC, jniles commented on test/integration/holidays.js
> +describe('(/holidays) The /holidays  API endpoint', function () {
Could you make sure this integration test suite respects ESLint?

2018-01-11 12:15 UTC, lomamech commented
@jniles

2018-01-11 22:19 UTC, jniles commented
@lomamech, it looks like these now have conflicts that need to be resolved.

2018-01-12 12:41 UTC, jniles commented
bors r+

2018-01-12 13:02 UTC, merged