Refactor: Fiscal Year
third-culture-software/bhima pull request #2542
Opened 2018-02-14 07:06 UTC by jniles

This PR essentially rewrites a lot of the Fiscal Year's core components.  The code was over a year old and a bit brittle.  Plus, a few more corner cases are considered (though not all of them #2397).  Here are the major changes:

 1. The user interface now include text instead of just buttons.  This makes it easier to click and see what the values of each button are.  They are hidden on small screen sizes, though.
 2. A complete rewrite of the core features of the `Tree` library.  This allows much greater flexibility without changing the tree's API at all.  This library has also been ported to the client as the `TreeService`.  In the future, we should figure out how to compile the same code to both the client and the server.
 3. Updated the opening balance modal to show totals on the title accounts and include a grid footer with the balances in the footer.  This feature uses the new `TreeService`.
 4. Opening balances can only be edited for the first year, so I've removed the button editing the fiscal year's opening balances.  If you are in the first fiscal year, it is open for edit.  Otherwise, it is closed.
 5. Removed the Income/Expense accounts from the opening balance modal.  Also ensured we are not posting balances for Title Accounts.
 6. Made all fiscal controllers and services pass ESLint checks on the client.
 7. Used "filter" icons instead of "search" icons for filtering the ui-grid (we do this in all other places in the application, it's confusing to do it differently here).
 8. A closed fiscal year can no longer be closed again.  The button is hidden/removed.  

Here are some screenshots:

![fiscalyearlist](https://user-images.githubusercontent.com/896472/36191440-748f53be-115d-11e8-8496-f955fc702b61.PNG)
_Fig 1: Fiscal Year List_

![beginningbalancemodalthatcanbeedited](https://user-images.githubusercontent.com/896472/36191483-b5788166-115d-11e8-92b2-08f35c42ef2a.PNG)
_Fig 2: First Fiscal Year's Opening Balance can be edited_

![beginningbalancemodalthatcannotbeedited](https://user-images.githubusercontent.com/896472/36191492-c24023cc-115d-11e8-9c81-b3e8d86d81a3.PNG)
_Fig 3: Other Fiscal Year's Opening Balances cannot be edited_

Closes #2349. 
Closes #2535. 
Closes #2536.

2018-02-14 14:21 UTC, mbayopanda requested changes
@jniles i did try to run the application but i have an error : Error: $injector:unpr Unknown Provider related to Tree.

Is it work correctly on your computer ?

2018-02-14 14:21 UTC, mbayopanda commented on client/src/modules/fiscal/fiscal.closingBalance.html
> +             <i class="fa fa-filter"></i> <span translate>FORM.BUTTONS.SEARCH</span>
👍

2018-02-14 14:21 UTC, mbayopanda commented on client/src/modules/fiscal/fiscal.list.html
> +              <a href="" ui-sref="users.list({ id : fiscal.user_id })" class="text-capitalize">
👍

2018-02-16 06:56 UTC, jniles commented
That's curious ... end to end tests would usually break if there is an $injector error.

On what controller does it happen?  I've tested most of the controllers in the fiscal year page.  Did you rebuild the client side?

2018-02-21 12:50 UTC, mbayopanda approved these changes
LGTM

2018-02-21 12:50 UTC, mbayopanda commented on client/src/js/services/TreeService.js
> +class TreeService {
👍

2018-02-21 12:58 UTC, mbayopanda commented
bors r+

2018-02-21 13:20 UTC, mbayopanda commented
@jniles could you fix the conflict and push again this branch

2018-02-21 13:44 UTC, jniles commented
Note: the import previous year balance is no longer necessary and should be removed in a subsequent PR.

2018-02-21 13:51 UTC, jniles commented
bors r+

2018-02-21 14:23 UTC, jniles commented
bors r+

2018-02-22 09:41 UTC, jniles commented
Hmm... weird build timeout issues.  I've increased the timeout, we'll see if Travis is happy.

bors r+

2018-02-22 19:54 UTC, jniles commented
bors r+

2018-02-23 06:26 UTC, jniles commented
So, it was code climate causing bors to fail since I had marked `master` as a "protected branch" and codeclimate as a required check.  Oops!  It looks like, since I changed the ESLint definitions, code climate marked all problems in the repository as problems with this branch...

Trying again w/o requiring codeclimate.

bors r+

2018-02-23 06:46 UTC, merged