refactor(Merge Weekend create and Confiuration)
third-culture-software/bhima pull request #3973
Opened 2019-10-31 14:22 UTC by lomamech

- Merge weekend create and configuration modals
- Remove not necessary Option and Test
- Update API in server side
- Updte Integration and E2E test

closes #3783

2019-11-01 07:49 UTC, lomamech commented
@mbayopanda can you review this PR

2019-11-01 12:12 UTC, jniles requested changes
This is great!  It looks like there may be a lot of legacy code hanging around after this change.  Please remove all functions/controllers/templates that this change will cause to never be used again.

2019-11-01 12:12 UTC, jniles commented on client/src/modules/payroll/weekend_configuration/templates/action.tmpl.html
> -      <a data-method="configure" ui-sref="configurationWeekend.config({id : row.entity.id})" href>
Can we remove the templates/controllers for this?  It seems like we can now delete whatever files make up the `configurationWeekend.config()` state.

2019-11-01 12:12 UTC, jniles commented on server/config/routes.js
> -  app.post('/weekend_config/:id/days', weekendConfig.createConfig);
👍

2019-11-01 12:12 UTC, jniles commented on server/controllers/payroll/weekendConfig/index.js
>    db.exec(sql, [data])
Go ahead and make this function `async/await` so you don't have to use `let`.  Like this:
```js
const { insertId } = await db.exec(sql, [data]);
const dataConfigured = configuration.map(id => ([id, insertId]));
await db.exec('INSERT INTO .... VALUES ?', dataConfigured]);
res.status(201).jsoin({ id : insertId });
```

2019-11-01 12:12 UTC, jniles commented on test/end-to-end/weekendConfig/weekend_config.spec.js
> -    await page.setWeekendConfig(updateWeekendConfigLabel);
Is there somewhere that you can remove these functions?  I don't think they will ever be used again.

2019-11-01 12:12 UTC, jniles commented on client/src/js/constants/bhConstants.js
> +      { id : 2, label : 'FORM.LABELS.WEEK_DAYS.TUESDAY', checked : false },
👍

2019-11-04 12:35 UTC, jniles reviewed
Awesome work.  Just one tiny try/catch and then I'll merge it.

2019-11-04 12:35 UTC, jniles commented on server/controllers/payroll/weekendConfig/index.js
> +async function create(req, res) {
This is better!  We still need to handle errors though.  To make sure these errors are handled, please add back in "next()' and wrap all your code in a try/catch block.  Like this:
```js
async function create(req, res, next) {
  try {
    // all your code
  } catch (e) {
    next(e);
  }
}
```

2019-11-04 12:35 UTC, jniles commented on test/end-to-end/weekendConfig/weekend_config.page.js
> -  async setWeekendConfig(label) {
👍

2019-11-04 12:35 UTC, jniles commented on test/integration/weekEndConfig.js
> -  it('POST /WEEKEND__CONFIG/:ID/DAYS should Set WeekEnds in Configuration', () => {
👍

2019-11-04 13:06 UTC, lomamech commented
@jniles I finished with the review

2019-11-04 13:19 UTC, jniles approved these changes

2019-11-04 14:40 UTC, lomamech commented
@jniles  I't done

2019-11-04 15:20 UTC, jniles commented
Excellent, responds to all my concerns.  Code looks good to me.

bors r+

2019-11-04 17:21 UTC, jniles commented
bors r+

2019-11-04 17:45 UTC, merged