feat(inventory) change report
third-culture-software/bhima pull request #4002
Opened 2019-11-18 15:12 UTC by jeremielodi

closes #3975

2019-11-18 15:12 UTC, kwilu commented
Hello @jeremielodi, it seems like you have referenced #3975 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #3975.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

<!-- fixCommitWarning -->

2019-11-20 10:33 UTC, jniles requested changes
Looks like there is quite a few lines copied from other reports that make this PR hard to read and evaluate.  Could you clean those up and ping me back for a review?

2019-11-20 10:33 UTC, jniles commented on client/src/modules/reports/generate/inventoryChange/inventoryChange.config.js
> +  vm.reportDetails = {
These looks like they are copied from somewhere.  Please remove all the code you didn't write and didn't use.

2019-11-20 10:33 UTC, jniles commented on client/src/i18n/en/report.json
> +      "TITLE" : "Inventory change report",
Let's call this "Inventory Changes Report"

2019-11-20 10:33 UTC, jniles commented on client/src/modules/reports/generate/inventoryChange/inventoryChange.config.js
> +  vm.onChangeShowInvoicedDetails = value => {
It doesn't look like you use any of this.  Please remove anything you don't use or need.

2019-11-20 10:33 UTC, jniles commented on server/controllers/inventory/reports/changes.js
> + * @overview Price Report
I don't think this is a price report.  Please update or remove these comments.

2019-11-20 10:33 UTC, jniles commented on server/models/migrations/next/migrate.sql
> +INSERT INTO unit VALUES
👍

2019-11-20 10:33 UTC, jniles commented on server/controllers/inventory/reports/changes.js
> +  let report;
You can move this `let` into a `const` in the `try/catch` block.

2019-11-20 10:33 UTC, jniles commented on server/controllers/inventory/reports/changes.js
> +      SELECT DISTINCT BUID(iv.uuid) as uuid, iv.text AS inventory_name
Why do we need the current inventory items?  Can't we just use the data in the logs?

2019-11-20 10:33 UTC, jniles commented on server/controllers/inventory/reports/changes.js
> +  removables.forEach(r => {
Just use lodash:
```js
_.omit(record, removables);
```

2019-11-20 10:33 UTC, jniles commented on server/controllers/inventory/reports/changes.js
> +    record.label = _.clone(record.text);
I don't think you need `_.clone` here.  I think you can just set them equivalent.

2019-11-20 10:33 UTC, jniles commented on server/controllers/inventory/reports/changes.js
> +  return record;
It looks like your entire `formatKeys` function could be:
```js
function formatKeys(record) {
  record.label = record.text;
  return _.omit(record, ['group_uuid', 'type_id', 'unit_id', 'text']);
}
```

Try it and see if that works.

2019-11-26 10:42 UTC, jniles commented
@jeremielodi what is the status of this PR?

2019-12-02 07:40 UTC, jniles commented
@jeremielodi can you make the changes to this PR for it to be merged?

2019-12-17 06:26 UTC, kwilu commented
Heads up @jeremielodi, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/IMA-WorldHealth/bhima/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](https://zulip.readthedocs.io/en/latest/git/troubleshooting.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

<!-- mergeConflictWarning -->

2020-01-14 15:02 UTC, jniles commented
@jeremielodi can you update this PR and fix things according to the review so we can merge?

2020-01-27 10:23 UTC, jniles commented
@jeremielodi, it doesn't look like you made any of the changes requested in the review.  Was there a reason for this?

2020-02-03 13:48 UTC, jniles approved these changes

2020-02-03 15:39 UTC, kwilu commented
Heads up @jeremielodi, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/IMA-WorldHealth/bhima/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](https://zulip.readthedocs.io/en/latest/git/troubleshooting.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

<!-- mergeConflictWarning -->

2020-02-03 16:16 UTC, jniles commented
bors r+

2020-02-03 16:57 UTC, merged