feat(stock): add option to view AMC calcs
third-culture-software/bhima pull request #5317
Opened 2021-01-27 15:04 UTC by jniles

Adds the ability to view the AMC/CMM calculations in the Articles in Stock Registry.  A summary of the information is presented for the user to examine and the explicit formula used to calculate the AMC is shown for the user to validate.

Closes #5291.

**Example using Algorithm 1**
![image](https://user-images.githubusercontent.com/896472/106009293-764def00-60b8-11eb-815b-a9dc7ca6941f.png)

**Example using Algorithm 2**
![image](https://user-images.githubusercontent.com/896472/106009860-1ad03100-60b9-11eb-8927-78a1ac5fcb1e.png)

**Example using Algorithm 3**
![image](https://user-images.githubusercontent.com/896472/106008578-ba8cbf80-60b7-11eb-8c0f-be436068fd5a.png)

**Example using Algorithm 4 (MSH)**
![image](https://user-images.githubusercontent.com/896472/106008076-3f2b0e00-60b7-11eb-99d1-a9ae9078847f.png)

**Example showing Algorithm (MSH) for 12 months**
![image](https://user-images.githubusercontent.com/896472/106008960-1eaf8380-60b8-11eb-97fd-9ee13524dc84.png)

2021-01-27 15:05 UTC, jniles commented
@jmcameron, this code isn't ready to be merged (I need to check translations and such), but could you give me a review on the user interface and user experience?   I've been looking at this too long to know if my ideas are any good or not.

2021-01-27 23:04 UTC, jmcameron approved these changes
I looked over the code and it looked good.
I tested this with the IMCK database it looks great.   I did spot-check several of the CMM calculations to make sure the numbers worked.    Everything looks great.

One small/cosmetic/ignorable suggestion:  Make the values for the CMM column to links to the same function the action menu invokes.  It could include a tooltip:  "Click here to see the details of this calculation.".  Ignore this if you think this would slow things down too much.

2021-01-28 07:55 UTC, jniles commented
@jmcameron thanks for your review!  Let me take a look at figuring out how to do that linking.

I'll ping you for a final review when that is done.

2021-01-28 10:05 UTC, mbayopanda reviewed
Good job @jniles 

I have noticed that : 

- The calculation of the Algo 3 doesn't match with what is displayed as an example **30.5 × (200 / 1) <> 32.97**: 
![image](https://user-images.githubusercontent.com/5445251/106120872-32f68d80-6157-11eb-99df-0b4d4d0a9fb7.png)

- The calculation of Algo 2 doesn't match with the example **30.5 × (200 / 185) <> 6100**
![image](https://user-images.githubusercontent.com/5445251/106121495-e95a7280-6157-11eb-962a-2a7bd5e12ddc.png)

It seems like the example for Algo 2 is given to Algo 3, and vice-versa

And the french translation

2021-01-28 10:05 UTC, mbayopanda commented on client/src/modules/stock/inventories/modals/amc.modal.js
> +      vm.isAlgo4 = vm.settings.average_consumption_algo === 'algo_msh';
👍🏽 Clean and nice

2021-01-28 10:40 UTC, jniles commented
Good catch @mbayopanda!  I'll switch those algorithm examples.

2021-01-28 20:18 UTC, jmcameron requested changes
I could not get the double-clicking on the CMM value to work.  I suggest making it a link with tooltip, if you have time.

I went back and did some more spot-checks (which I should have done the first time!).   The calculations for Alg 1 and 4 seem fine.  But I'm seeing errors on 2 and 3.  See below.

![image](https://user-images.githubusercontent.com/62145/106193639-a18d1880-6162-11eb-9c0d-a0af66957295.png)

![image](https://user-images.githubusercontent.com/62145/106193734-c3869b00-6162-11eb-8761-6e683e6629e1.png)

2021-01-29 08:06 UTC, jniles commented
Okay, this confusion that @jmcameron pointed out and that @mbayopanda pointed out is because we change the names of our algorithms somewhere between the concept note, the translation, and the calculation.  I'll try to track it all down.

2021-02-01 13:14 UTC, jniles commented
@jmcameron can you give me another review?

I've integrated the french language translations and attempted to polish up the double-click experience.  I believe this should solve the issues you were having with double-clicking.

I would prefer not to put a label/title/tooltip on it for performance reasons.  I also don't think it enhances the experience that much after testing it myself, and may hurt a users ability copy/paste as it gets in the way.  If you feel strongly about it, I can put it in.

For completeness, here is what the current version looks like:

![image](https://user-images.githubusercontent.com/896472/106463459-b84faa00-6497-11eb-8c60-cc032256f67b.png)


----

I've noticed that in Vanga's database, the min/max isn't being properly computed, making everything either "in stock" or "over maximum".  I'm taking a look at that.

2021-02-01 13:16 UTC, jniles commented
Actually, I just realized the screen shot I posted doesn't make any sense.  How can we have more days of stock consumption than we do of stock available?

Hmm....  I hope our CMM calculation is working.

2021-02-01 16:13 UTC, jmcameron approved these changes
I tried the CMM double-click and it works fine now.  
Your decision to not add a tool-tip makes sense.
Let me know if you want me to review it again after straightening out the CMM calculations.

BTW, on the last screen-shot you have of the CMM calculations for Algo 4:  The fact that algorithms 1 and 2 have much bigger numbers than 3 and 4 is concerning too.

2021-02-01 19:36 UTC, jniles commented
@jmcameron, thanks for your review.  I've updated the base branch so that we will merge this off the main branch.

2021-02-01 19:36 UTC, jniles commented
bors r+

2021-02-01 19:41 UTC, merged