Adding search by action and exports
third-culture-software/bhima pull request #5828
Opened 2021-08-06 09:44 UTC by mbayopanda

This PR adds:
- Export option for CSV and Excel
- Search by type of action (delete or edit)

Close #5827

2021-08-06 12:06 UTC, jniles reviewed
The CSV export works well 👍 

Could you do some updates to the XLSX export to make it more useful?  Users will want access to the information in the `value` section, but it currently isn't usable to them.

2021-08-06 12:06 UTC, jniles commented on server/config/routes.js
> +  app.get('/reports/finance/journal/log', financeReports.journal.journalLogReport);
:+1:

2021-08-10 06:06 UTC, jniles requested changes
Have you tested this with the vanga database?  It crashes as is, but when I fixed the crash, it doesn't properly display all the information:

![image](https://user-images.githubusercontent.com/896472/128816449-f1f3d346-f178-41fe-a8fb-024b901afa13.png)

Since they are the ones who will use this information, let's try to fix this before merge.

2021-08-11 23:21 UTC, mbayopanda commented
> 
> 
> Have you tested this with the vanga database? It crashes as is, but when I fixed the crash, it doesn't properly display all the information:
> 
> ![image](https://user-images.githubusercontent.com/896472/128816449-f1f3d346-f178-41fe-a8fb-024b901afa13.png)
> 
> Since they are the ones who will use this information, let's try to fix this before merge.

Thank you @jniles for the review and the catch

2021-08-11 23:21 UTC, mbayopanda commented
@jniles changes landed

2021-08-12 08:20 UTC, jniles commented
Hmm... still not getting any descriptions from the Vanga database in the Excel export.  Let me see if I can work on it.

2021-08-12 10:25 UTC, jniles commented
Okay, got it working:

![image](https://user-images.githubusercontent.com/896472/129181405-e3bd4721-236b-40b6-ba27-a4db4daf59b1.png)

![image](https://user-images.githubusercontent.com/896472/129181460-e6740761-3350-4985-b80f-e4f46b78091e.png)


@mbayopanda take a look at my changes.  If they are good with you, we can merge this.

2021-08-12 14:43 UTC, mbayopanda commented
It's LGTM 👍🏽

2021-08-13 08:17 UTC, jniles approved these changes
LGTM.

Bors r+

2021-08-13 08:24 UTC, merged