Use of decimal for stock minimum months
third-culture-software/bhima pull request #5877
Opened 2021-08-24 13:01 UTC by mbayopanda

This PR is related to #5876

Close #5876

2021-08-24 13:17 UTC, jmcameron requested changes
I think you need to also do similar input form modifications on Stock > Stock Settings  (client/src/modules/stock/settings/stock-settings.html).

2021-08-24 13:17 UTC, jmcameron commented on client/src/modules/depots/modals/depot.modal.html
> +        ng-model="DepotModalCtrl.depot.min_months_security_stock" type="number" min="0" autocomplete="off" required>
We should consider making min="0.00001" (or similar) to prevent acceptance of zero.

2021-08-26 07:26 UTC, jniles commented
bors try

2021-08-26 07:41 UTC, jmcameron reviewed
The code changes look good (see my notes).

I tested this with bhima_test.  Changing the values in stock settings works fine.  

However when I tried it with the Depot editor, it seems like the values are set properly, but when I edit again, I see that the value "Default Purchase order interval (in months)" is still 0 (I set it to 0.25).  See:
![image](https://user-images.githubusercontent.com/62145/130921800-5e67ea18-ecd6-4cac-bcca-ac0922f0115c.png)

2021-08-26 07:41 UTC, jmcameron commented on client/src/modules/stock/settings/stock-settings.html
> +              ng-change="StockSettingsCtrl.setMonthAverage(value)" min="0.00001">
Not sure it matters, but should these include:  type="number" 
?

2021-08-26 07:42 UTC, jniles commented on client/src/modules/stock/settings/stock-settings.html
> +              ng-change="StockSettingsCtrl.setMonthAverage(value)" min="0.00001">
They do - you missed it.  It's up above.

2021-08-26 07:44 UTC, jniles commented on server/models/schema.sql
>    `default_purchase_interval` SMALLINT(5) NOT NULL DEFAULT 0,
This needs to be DECIMAL as well.  That is the problem @jmcameron ran into.

2021-08-31 12:42 UTC, mbayopanda commented on server/models/schema.sql
>    `default_purchase_interval` SMALLINT(5) NOT NULL DEFAULT 0,
I had done changes only in migrate.js

2021-08-31 13:11 UTC, jniles approved these changes
This worked for me.

bors r+

2021-08-31 13:14 UTC, merged