fix(stock): ensure correct movement filter text
third-culture-software/bhima pull request #6635
Opened 2022-05-25 10:10 UTC by jniles

This commit ensures that the entry/exit movement filter shows the correct values when searching for the movement direction.

Closes https://github.com/IMA-WorldHealth/bhima/issues/6445.

2022-05-25 10:31 UTC, jmcameron requested changes
The code looks okay.   I tested it and it works.
But I have one suggestion.   The attached filter setting is a bit convoluted to my eye:
![image](https://user-images.githubusercontent.com/62145/170242386-98219067-968c-4cd6-a54f-794cf06777c6.png)

I think the filter should show "Input=Yes" or "Output=Yes", not "Output=No" for input-only.

2022-05-25 10:31 UTC, jmcameron commented on client/src/modules/stock/movements/modals/search.modal.html
> +                <input type="radio" name="movement_direction" id="entry" ng-value="0" ng-model="$ctrl.searchQueries.is_exit">
Well... That is tricky!

2022-05-25 10:31 UTC, jmcameron commented on client/src/modules/stock/movements/templates/io.cell.html
> +    <span class="label" ng-class="{ 'label-danger' : row.entity.is_exit === 1, 'label-success' :  row.entity.is_exit === 0 }">
Nice

2022-05-26 06:43 UTC, jniles commented
I agree.  I was lazy here.

We may need to build tooling for that, since it isn't a use case we've explored before - not sure how long it will take me, but I will give it a whack.

2022-06-01 07:23 UTC, jmcameron approved these changes
Will make a new issue for the awkward filter text.

2022-06-01 07:23 UTC, jmcameron commented
bors r+

2022-06-01 07:27 UTC, merged