chore(stock): improve stock settings terminology
third-culture-software/bhima pull request #6639
Opened 2022-05-26 10:47 UTC by jniles

This commit rewrites and improves both the layout and language used on stock settings, the depot permission modal, and a few select locations to ensure that the English text is clear.

Closes #6520.

Here is what it looks like now:
![image](https://user-images.githubusercontent.com/896472/170473346-80e38ca7-5763-493d-b544-6b65afb917be.png)

2022-05-26 13:52 UTC, jmcameron requested changes
I reviewed the language changes and most were excellent.  I added some suggestions for a few of them.   

I found a translation problem in the Stock Requisition create/edit modals:
![image](https://user-images.githubusercontent.com/62145/170500697-b8f3c95f-4ed2-4dee-955b-f5d157d3d867.png)

I tested this and reviewed the stock settings page.   It seemed fine.  However, I suggest:
- Move "Minimum delivery delay" setting above "Security stock multiplier" since the MDD is used to compute the value that SSM is applied to.


There are a couple of other missing translation items in the translations. These are not related to this PR, but this is good chance to fix them anyway.  Or we can add an issue to fix them.

```
   $ node utilities/translation/tfcomp.js client/src/i18n/en client/src/i18n/fr
   Missing from /home/jmcameron/Bhima/client/src/i18n/fr/asset.json:
     ASSET.SHOW_ONLY_LAST_SCAN

   Missing from /home/jmcameron/Bhima/client/src/i18n/en/report.json:
     REPORT.STOCK_VALUE.THROUGH

   Missing from /home/jmcameron/Bhima/client/src/i18n/fr/report.json:
     REPORT.THROUGH
```

2022-05-26 13:52 UTC, jmcameron commented on client/src/i18n/en/stock.json
> +    "USE_OF_STOCK_WAC" : "This value is calulated automatically using the Weighted Average Cost (WAC) algorithm.",
👍

2022-05-26 13:52 UTC, jmcameron commented on client/src/i18n/en/stock.json
> +      "PRODUCTS_IN_OVERSTOCK" : "Products overstocked"
👍

2022-05-26 13:52 UTC, jmcameron commented on client/src/i18n/en/stock.json
> +    "CREATE_SUCCESS" : "Successfully created the assignment",
Nice.  Friendlier language!

2022-05-26 13:52 UTC, jmcameron commented on server/controllers/stock/core.js
> + *   S_MIN: Minimum stock - typically the security stock (depends on the depot), plus some multiplier.
Instead of 'plus', perhaps say "with"?

2022-05-26 13:52 UTC, jmcameron commented on server/controllers/stock/core.js
> +    // FIXME(jniles): rename min_months_security_stock variable since it doesn't depend on months
Can we fix this in this PR?

2022-05-26 13:52 UTC, jmcameron commented on client/src/i18n/en/stock.json
> +    "DEFAULT_MIN_MONTHS_SECURITY_STOCK_HELP_TEXT": "This value is multiplied by the security stock to determine the minimum quantity of stock to keep in the depot (Smin) using the formula (Smin = SS
Suggestion:
- Change "multiplied by the security stock" to "multiplied by the value of the security stock (SS)"...

2022-05-26 13:52 UTC, jmcameron commented on server/controllers/stock/core.js
> + *   S_SEC: Security Stock - the amount of stock needed to survive a reorder period without stockout.
👍

2022-05-27 09:11 UTC, jniles commented on server/controllers/stock/core.js
> +    // FIXME(jniles): rename min_months_security_stock variable since it doesn't depend on months
I prefer to do the translation changes and DB changes in two different PRs.  I'll also improve the requisition performance.

2022-05-27 09:18 UTC, jniles commented
@jmcameron this is ready to be reviewed again.

2022-05-27 10:10 UTC, jmcameron commented on client/src/i18n/en/stock.json
> +    "USE_OF_STOCK_WAC" : "This value is calulated automatically using the Weighted Average Cost (WAC) algorithm.",
Looks good

2022-05-27 10:12 UTC, jmcameron commented on server/controllers/stock/core.js
> +    // FIXME(jniles): rename min_months_security_stock variable since it doesn't depend on months
Sounds good

2022-05-27 10:15 UTC, jmcameron approved these changes
Checked the changes and they all look good.

2022-05-27 10:15 UTC, jmcameron commented
bors r+

2022-05-27 10:18 UTC, merged