chore(colors): remove duplicate colors
third-culture-software/bhima pull request #7161
Opened 2023-07-23 18:31 UTC by jniles

This commit removes duplicate colors from the ColorService.

Closes #7018

2023-07-24 07:18 UTC, jmcameron requested changes
I noticed this problem while converting the E2E tests.   Thanks for working on it!

The changes mostly look good.  

I tested it using the bhima_test DB.  I noticed that the colors that are from i18n COLORS.* are capitalized.  Could you please modify the .json file and uncapitalize them.  Also I think GRAY is a duplicate that could be deleted.

Thanks!

2023-07-24 07:18 UTC, jmcameron commented on client/src/js/services/color.js
> -    { name : $translate.instant('COLORS.AQUA'), value : '#00ffff' },
Thank you!

2023-07-25 06:25 UTC, jmcameron requested changes
Thanks for the changes.  I hate to be picky, but could I ask you to delete the duplicate 'gray' color and sort the list of colors alphabetically.  And why do we have translations for some colors and not others (legacy?).

2023-08-03 14:51 UTC, jniles commented
@jmcameron this is ready to go 👍

2023-08-03 15:01 UTC, jmcameron commented
bors r+

2023-08-03 15:16 UTC, jniles commented
Looks like MySQL failed to initialize - I'll restart it.

bors r+

2023-08-03 15:20 UTC, merged