User Refactoring
third-culture-software/bhima pull request #729
Opened 2016-09-16 10:55 UTC by DedrickEnc

This PR implements the user refactoring, the full description will be provided at the end

- [x] Restructuring folder and files and renaming

- [x] UI concerns and ```$state``` using

- [ ] Polishing UI and Using ```NotifyService```

- [ ] jshint

- [ ] Integration test

- [ ] end to end test

2016-09-26 08:27 UTC, DedrickEnc commented
@jniles

2016-09-26 08:43 UTC, jniles commented on client/src/i18n/en.json
> -  "PERMISSIONS": {
This has needed to happen for along time :+1:

2016-09-26 08:44 UTC, jniles commented on client/src/partials/accounts/accounts.js
> +  'LanguageService', '$state'
I think this is left over from our debugging session.  Can you remove it?  And the `console.log()` below.

2016-09-26 08:44 UTC, jniles commented on client/src/partials/journal/modals/transaction.html
> +transaction
Can you remove this file from the PR?

2016-09-26 08:46 UTC, jniles commented on client/src/partials/users/UserEditPasswordModal.html
> +  <div ng-form="PasswordForm">
This form should have a `bh-form-defaults`.

2016-09-26 08:47 UTC, jniles commented on client/src/partials/users/UserEditPasswordModal.js
> +    if (!passwordForm.$dirty) { return; }
Why is this check necessary?

2016-09-26 08:47 UTC, jniles commented on client/src/partials/users/UserEditPasswordModal.js
> +    .catch(function (err) {
This can just be `.catch(Notify.handleError)`

2016-09-26 08:48 UTC, jniles commented on client/src/partials/users/UserEditPasswordModal.html
> +  <button id="password-submit" type="submit" class="btn btn-sm btn-success" ng-click="UsersPasswordModalCtrl.submit(PasswordForm)">{{ "FORM.BUTTONS.SUBMIT" | translate }}</button>
Can this use a `bh-loading-button`?  It would be a much better user experience.

2016-09-26 08:50 UTC, jniles commented on client/src/partials/users/userPermission.modal.js
> +      .catch(function (err){Notify.handleError(err);});
I think these are cleaner as `catch(Notify.handleError)`.

2016-09-26 08:50 UTC, jniles commented on client/src/partials/users/userPermission.modal.js
> +  function checkboxOffset(depth) {
Interesting :+1:

2016-09-26 08:56 UTC, jniles reviewed
@DedrickEnc, I have completed an initial review.  The code is pretty good.

I'll take a harder look at the functionality in a future review.  At the moment, here is some feedback:
1. Please remove all code related to Trial Balance/Journal Transactions from this PR.  It will be easier to know what is important in the review.
2. If possible, make all your forms that submit HTTP requests use `bhLoadingButton`.  To use `bhLoadingButton`, you'll need to use `bhSubmit`.  Also remember to use `bhFormDefaults` directive to make sure forms behave correctly.
3. Make sure all your buttons are the same size.  The preferred size is `btn btn-default`.

Your handling of `$state` looks excellent.  Very good job!

After these changes are made, I'll take another look.

2016-09-26 11:58 UTC, DedrickEnc commented on client/src/partials/users/UserEditPasswordModal.js
> +    if (!passwordForm.$dirty) { return; }
To avoid the modal to be closed directly

2016-09-26 13:14 UTC, DedrickEnc commented
@jniles
changes are applied

2016-09-26 14:04 UTC, jniles commented on client/src/partials/users/userPermission.modal.html
> +        <div class="checkbox" ng-style="UserPermissionModalCtrl.checkboxOffset(unit.depth)">
The spacing is really big for this modal, due to the combination of `list-group-item` and `checkbox` classes.  I propose that you had `style="margin:0"` to the `<div class="checkbox" ...>` DOM node.

In the image below, I've changed `Caisses et Banques` to using `margin:0` for comparison.  Let me know what you think.
![permissionsmargins](https://cloud.githubusercontent.com/assets/896472/18837036/3ddc1434-83fa-11e6-91bf-1ca9d8ab90af.png)
_Fig 1: Spacing Difference in `list-group-item`s_

If you think it is too small, you can pick a size smaller than 10px (which is what it is now) that you think looks best.

2016-09-26 14:05 UTC, jniles commented on client/src/partials/users/userPermission.modal.html
> +            {{ "USERS.SUPER" | translate }}
This would look much better if it were **bold**.  That way it looks important - at the moment, it just looks like any of of the top level folders.

2016-09-26 14:13 UTC, jniles requested changes
@DedrickEnc, thanks for cleaning up those other files.  It's much easier to review now!

The Users and Permissions grid is much better than it used to be.  Awesome :+1:.

There are still some bugs that I've commented inline.  Some of the validation doesn't work properly.

Here are the issue to address before merge:
1. I'm not a big fan of putting a modal on top of a modal.  I've never seen an application do that.  Could you update this to either (a) dismiss the editing modal and bring on the permissions modal or (b) just put the password inline to the editing modal?
2. The `<select multiple>` is a really terrible user experience (this was always the case, not specific to your code).  Could you try using the [multiple selection](http://angular-ui.github.io/ui-select/demo-multiple-selection.html) provided with `ui-select` to see if that provides a better user experience?
3. There are no `Notify.success()` messages when permissions or users are updated.  Could you add a success message?
4. The `feedback` icons behave very strangely.  Could you look into making them look like [bootstrap's examples](http://getbootstrap.com/css/#forms-control-validation)?

After these changes land, I'll be very happy to have this merged.

2016-09-26 14:13 UTC, jniles commented on client/src/partials/users/user.modal.js
> +    $state.go('users.list', null, {reload : false});
Just FYI, `{reload:false}` is the [default value](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state#methods_go).  You could express the same thing by `$state.go('users.list');`.

2016-09-26 14:13 UTC, jniles commented on client/src/partials/users/UserEditPasswordModal.html
> +<form name="PasswordForm" bh-submit="UsersPasswordModalCtrl.submit(PasswordForm)" bh-form-defaults novalidate>
:+1:  Much better.

2016-09-26 14:13 UTC, jniles commented on client/src/partials/users/UserEditPasswordModal.js
> +    if (!passwordForm.$dirty) { return; }
This `$dirty` check is unnecessary.  The `required` attribute will mark the form `$invalid`.  The reason you have it is a syntax error in the line directly about it.  It should be `if (passwordForm.$invalid)`, not `if (passwordForm.invalid)`.

2016-09-26 14:13 UTC, jniles commented on client/src/partials/users/user.modal.js
> +    if (userForm.invalid) { return; }
All of these should be `$invalid` checks.  Currently, the form lets an invalid user get signed up.

2016-09-26 14:13 UTC, jniles commented on client/src/partials/users/user.modal.js
> +      vm.user.passwordVerify.length &&
You actually don't need to do all these checks on `passwordVerify`.  This will work:

``` js
return vm.user.password && vm.user.password.length > 0 && vm.user.password === vm.user.passwordVerify;
```

Since the last check is an equality check, if it is true, then the length and existence checks must be okay.

2016-09-26 14:13 UTC, jniles commented on client/src/partials/users/users.html
> +          class="btn btn-default btn-sm"
This would look better without the `btn-sm`.

2016-09-26 14:13 UTC, jniles commented on client/src/partials/users/users.js
> +      Notify(err);
`NotifyService` does not work like this...

2016-09-26 14:13 UTC, jniles commented on client/src/partials/users/users.routes.js
> +        params : {
Could you set `creating : false` here and not have to specify `creating:false` in the controller?

2016-09-26 14:13 UTC, jniles commented on test/end-to-end/user/user.spec.js
> +  it('refuses to update the same user', function () {
To be clearer, I think you mean "refuses to update a user when no changes have been made".

2016-09-27 10:24 UTC, DedrickEnc commented on client/src/partials/users/user.modal.js
> +    if (userForm.invalid) { return; }
I am not understanding

2016-09-27 10:29 UTC, DedrickEnc commented on client/src/partials/users/user.modal.js
> +      vm.user.passwordVerify.length &&
These code was reviewed and merged, it was written by some one else not me, I was just focusing on what the issue #729 said.

2016-09-27 10:29 UTC, jniles commented on client/src/partials/users/user.modal.js
> +    if (userForm.invalid) { return; }
The `invalid` property does not exist on AngularJS forms.  It's called `$invalid`.  [Documentation](https://docs.angularjs.org/api/ng/type/form.FormController#$invalid).

2016-09-27 10:33 UTC, jniles commented on client/src/partials/users/user.modal.js
> +      vm.user.passwordVerify.length &&
Okay, no problem.

2016-09-27 10:37 UTC, DedrickEnc commented on client/src/partials/users/user.modal.js
> +      vm.user.passwordVerify.length &&
I will see that

2016-09-27 11:10 UTC, DedrickEnc commented on client/src/partials/users/UserEditPasswordModal.js
> +    if (!passwordForm.$dirty) { return; }
But what will happen if the user try to submit a record which is not edited.

2016-09-27 11:24 UTC, DedrickEnc commented on client/src/partials/users/users.routes.js
> +        params : {
Where am I specify ```creeating : false``` in the controller?

2016-09-27 11:34 UTC, jniles commented on client/src/partials/users/users.routes.js
> +        params : {
https://github.com/IMA-WorldHealth/bhima-2.X/pull/729/files#diff-cb39a35f84cd36605406b6d1879f11ceR34

2016-09-27 11:35 UTC, jniles commented on client/src/partials/users/users.routes.js
> +        params : {
Note: I've never tested this method, so it might not work.

2016-09-27 11:52 UTC, jniles commented on client/src/partials/users/users.routes.js
> +        params : {
So, I just tested it with Billing Services, and my proposal will not work.  Don't work about it.

2016-09-28 22:46 UTC, DedrickEnc commented
@jniles
You can have a look

2016-09-29 08:31 UTC, jniles approved these changes
@DedrickEnc the code LGTM.

I think you can do the `repeat` with a regular Angular filter.  Can you try that really quick before I merge?  If we don't need `propsSearch`, it would be best to remove it before putting it in `master`.

LGTM :+1:

2016-09-29 08:31 UTC, jniles commented on client/src/partials/users/user.modal.html
> +        <ui-select-choices repeat="project.id as project in UserModalCtrl.projects| propsSearch:{name: $select.search}">
Does Angular's [filter](https://docs.angularjs.org/api/ng/filter/filter) not work in this case?

It seems to me this should work fine:
```html
<ui-select-choices repeat="project.id as project in UserModalCtrl.projects | filter:{name: $select.search}">
```

2016-09-29 08:31 UTC, jniles commented on client/src/partials/users/userPermission.modal.html
> +        <label class="label label-warning">{{ "USERS.PERMISSIONS" | translate }}</label>
Just FYI, there is also a class ["badge badge-warning"](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/less/bhima-bootstrap.less#L144) created specifically for this usage. The "label" class is often too small and not properly centered.

It was developed in response to [#263](https://github.com/IMA-WorldHealth/bhima-2.X/issues/263).

2016-09-29 09:21 UTC, DedrickEnc commented on client/src/partials/users/user.modal.html
> +        <ui-select-choices repeat="project.id as project in UserModalCtrl.projects| propsSearch:{name: $select.search}">
I will try it

2016-09-29 09:22 UTC, DedrickEnc commented on client/src/partials/users/userPermission.modal.html
> +        <label class="label label-warning">{{ "USERS.PERMISSIONS" | translate }}</label>
Ok, will change it during this fix

2016-09-29 09:40 UTC, DedrickEnc commented
@jniles 
The update was landed

2016-09-29 11:01 UTC, jniles commented
Changes LGTM.  Thanks!

2016-09-29 11:02 UTC, merged