Inventory add updated_by
third-culture-software/bhima pull request #7414
Opened 2024-01-11 16:46 UTC by Ebed-meleck

Add the required note after price change
Add the column updated_by for the last user updated item

@jniles Did I answer this #7404

2024-01-16 07:25 UTC, jmcameron requested changes
The code looks good.

I will wait for the author to change 'require' to 'required' (for bhUserSelect) before testing.

2024-01-16 07:25 UTC, jmcameron commented on client/src/modules/inventory/list/modals/search.modal.html
> +            require="false"
This is an error:  it should be 'required'.

2024-01-16 10:11 UTC, jmcameron requested changes
The code looks good. 
The tests pass.
I  tested this on my dev computer with bhima_test and it works correctly.

I noticed that two English translation terms are missing:
![image](https://github.com/IMA-WorldHealth/bhima/assets/62145/d1f8254a-d66d-4091-b153-365e5d3d23c4)

Note that it is easy to check for missing translation terms by running: `npm run check:lang`

Once the translation item is fixed, this PR is ready to merge.

2024-01-16 10:11 UTC, jmcameron commented on client/src/modules/inventory/list/modals/search.modal.html
> +            required="false"
👍

2024-01-16 13:15 UTC, jmcameron approved these changes
Looks good.

2024-01-16 13:15 UTC, jmcameron commented on client/src/i18n/en/form.json
> +            "LAST_USER_UPDATE" : "Last edited by",
Thanks

2024-01-16 13:15 UTC, merged

2024-01-22 05:56 UTC, Ebed-meleck commented
Closed #7404