Import payroll configuration from excel
third-culture-software/bhima pull request #7662
Opened 2024-07-11 17:18 UTC by lomamech

- Implementation of the functionality allowing the import of the configuration made from the csv file

closes https://github.com/IMA-WorldHealth/bhima/issues/7655

2024-07-11 20:29 UTC, lomamech commented
**Detailed Explanation**

1. **Enable Index Payment System Mode:**

- Navigate to Payroll Settings.
- Enable the Index Payment System mode.

2. **Modify Payroll Rubrics:**

Go to Payroll Rubric Management.
- Select and edit the rubrics **ACOMPTE SUR SALAIRES** and **FRAIS SCOLARITÉ.**
- Check the options This rubric **is an index** and This index **is to be entered.**

3. **Configure Rubrics in Payroll Rubric Configuration**:
   - Navigate to `Payroll Rubric Configuration`.
   - Edit `CONFIGURATION DES RUBRIQUES (INDICES)` and select `ACOMPTE SUR SALAIRES` and `FRAIS SCOLARITÉ`.
 
![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/1ff79822-6834-4e8b-9c63-ed2fe59ebeec)


4. **Create New Pay Period**:
   - Create a new pay period for July 2024 by going to `Pay Period Configuration`.
![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/eb0fa656-2315-4173-93f4-a4da2eb1fda0)

5. **Access Multiple Payroll (Index-based) Module**:
   - Navigate to the `Indexes` folder.
   - Access the `Multiple Payroll (index-based)` module.
   - Select the newly created pay period to view a grid with the configured employees.
![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/35b07ae9-8b32-476b-95f9-ed981643c87f)

6. **Download Template File**:
   - Click on the menu and select the `Download template file` option.
   - This will download a CSV file with the columns and employees for the selected pay period.
![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/974d14d4-99ae-4b58-84b2-199b46ea4cf5)

7. **Upload the Filled Template File**:
   - Return to BHIMA and click on the menu again.
   - This time, select the `Upload payroll configuration` option to upload the filled template file.

![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/2deded14-a7b7-4fdf-b5bc-112d03a8b961)

![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/a998097f-30a1-4293-a24a-e8876d603971)

 After selecting the CSV file, the configuration will be automatically processed and applied successfully.


![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/222408fd-b357-426a-82e9-28548c8ea186)

2024-07-11 20:37 UTC, lomamech commented
@jmcameron @jniles You can review this PR

2024-07-12 08:44 UTC, jmcameron requested changes
The code looks okay.
All regular and end-to-end tests pass.
When I did step 5, I noticed that search options indicators were not be handled correctly:
![image](https://github.com/user-attachments/assets/987e0ed0-1587-4542-8ec1-4105c1b83c7a)

I had problems on step 6.  When I edited the downloaded template file, it looked like this
![image](https://github.com/user-attachments/assets/a7ec219c-151b-4cf2-a17c-88093e3ce5fb)

When I tried uploading it, I got this error:
![image](https://github.com/user-attachments/assets/f8489d26-8b9a-4a7d-8a42-68b2c1173be4)

Please rename the downloaded template file from "Download the template file 7_12_2024.csv" to something like "payroll_configuration_template_7_12_2024.csv".  The downloaded filename should be a noun, not a command.

Please delete the yarn.lock file from your branch, and use 'npm to install the dependencies'.  We no longer use yarn for installing dependencies.

Thanks

2024-07-12 13:48 UTC, jniles reviewed
Great work on this @lomamech!  I added some clean up code comments.  The only two that I care about are:
 1. Adding in the debug module (this will be incredibly helpful when things break in production as they always do).
 2. Using consistent async/await.

I haven't run the code to test it yet, but I see that @jmcameron gave you that review.

2024-07-12 13:48 UTC, jniles commented on client/src/modules/multiple_payroll_indice/multiple_payroll_indice.js
> +    MultiplePayroll.importConfigModal({ payroll_configuration_id : vm.payrollConfigurationId }).then(result => {
Should this have some sort of error handling?

2024-07-12 13:48 UTC, jniles commented on server/controllers/payroll/multiplePayrollIndice/parameters.config.js
> +    data.forEach(item => {
You might consider using a `Array.prototype.map()` here.

```js
const arrayDataFormated = data.map(item => {

  // ... process as needed ...
  
  return dataElement;
});
```

2024-07-12 13:48 UTC, jniles commented on server/controllers/payroll/multiplePayrollIndice/parameters.config.js
> +    transaction.execute()
You are already using `async/await` in this function, go ahead and use it here.  This code would then read:

```
try {
const record = await transaction.execute();

// etc 
} catch (e) {
  next(e)
}
```

2024-07-12 13:48 UTC, jniles commented on server/controllers/payroll/multiplePayrollIndice/parameters.config.js
> +        const rubPayroll = record[0];
It might be nice to use destructing here so that we know what properties are in `record`. 

```js
transaction.execute()
  .then(([rubPayroll, empPayroll, rubPayrollConfig]) => {
    const checkColumnFormated = Object.keys(arrayDataFormated[0]).length;
    // etc...
  });
```

2024-07-12 13:48 UTC, jniles commented on server/controllers/payroll/multiplePayrollIndice/parameters.config.js
> + * Import Payroll Configuration for a payroll configuration
This code looks good overall!

One thing that would help a lot in debugging production bugs is using the `debug` module.  Could you import `debug`, and give it a name like:
```js
cont debug = require('debug')('payroll:import');
```

And then use it to indicate what is happening in the loop?

For example, you could do something like:
```js
debug(`Received a CSV file with ${data.length} rows.`);

// later:

let checkValidEmployee = 0;
empPayroll.forEach(emp => {
  arrayDataFormated.forEach(dt => {
    if (emp.employee_display_name.toLowerCase() === dt.employee.toLowerCase()) {
       debug(`Configuring payroll for ${emp.employee_display_name}.`);
       checkValidEmployee++;
    }
  });
});
```

If you add in a few of these debug messages, particularly where you are looping through records, we will be able to diagnose production issues much easier.

2024-07-12 13:48 UTC, jniles commented on server/controllers/payroll/multiplePayrollIndice/parameters.config.js
> +        transactionOperation.execute()
This could also be `async/await` to clean up this `.then()` series of loops.

2024-07-12 13:48 UTC, jniles commented on server/controllers/payroll/multiplePayrollIndice/parameters.config.js
> +            res.status(200).json();
If you aren't returning any data, you should use `res.sendStatus(204)`, since HTTP 204 indicates [No Content](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/204).

2024-07-13 10:31 UTC, lomamech commented
> I noticed that search options indicators were not be handled correctly:

This error often appears randomly, I will try to reproduce it and see how to correct it

2024-07-13 18:30 UTC, lomamech commented on server/controllers/payroll/multiplePayrollIndice/parameters.config.js
> + * Import Payroll Configuration for a payroll configuration
> One thing that would help a lot in debugging production bugs is using the `debug` module. Could you import `debug`, and give it a name like:

I don't really understand what I have to do in relation to debugging.

2024-07-13 18:31 UTC, lomamech commented on server/controllers/payroll/multiplePayrollIndice/parameters.config.js
> + * Import Payroll Configuration for a payroll configuration
@jniles I need an explanation

2024-07-16 06:20 UTC, jmcameron approved these changes
Normal and end-to-end tests pass.
Tested per directions and it works fine.
Ready for merger after rebasing/squashing commits.

2024-07-16 09:21 UTC, merged