ui grid in complex voucher
third-culture-software/bhima pull request #794
Opened 2016-10-10 10:55 UTC by mbayopanda

This PR : 

- Replace `html` table by a `ui-grid`
- Add payment reference and fixing
- Add a search button in the reference modal for finding references 
- Replace the `typeahead` by a `ui-select` in entity modal 
- Fix grid resizing
- Fix transaction reference

2016-10-10 11:56 UTC, jniles requested changes
@mbayopanda, this looks pretty good.

I'm concerned about putting a ui-select in the `entity` modal.  If we have thousands of patients, this may become a performance bottleneck (by default, all patients will be rendered as debtors in the dropdown.  While `ui-select` is a very useful and powerful tool, I don't think that's a good use case.

2016-10-10 11:56 UTC, jniles commented on client/src/partials/templates/modals/findEntity.modal.html
> +        <ui-select
:+1:  Nice improvement.

2016-10-10 11:56 UTC, jniles commented on client/src/partials/templates/modals/findReference.modal.js
> +          '{{ row.entity.amount | currency: grid.appScope.enterprise.currency_id }}' +
:+1:

2016-10-10 11:56 UTC, jniles commented on client/src/partials/vouchers/complex.html
> +            ui-grid-resize-columns>
I don't think resizing columns is a good idea on a grid with inputs.  What do you think?  Is it really necessary?

2016-10-11 12:11 UTC, mbayopanda commented
@jniles could you review this PR

2016-10-11 12:28 UTC, jniles commented on test/end-to-end/shared/FormUtils.js
> +  uiSelectAppended: function uiSelectAppended(model, label, anchor) {
Cool!

2016-10-11 12:28 UTC, jniles commented on test/end-to-end/shared/FormUtils.js
> +    anchor = anchor || $('body');
I don't think you ever use the anchor.  Could it be removed?

2016-10-11 12:29 UTC, jniles approved these changes
LGTM

2016-10-11 12:29 UTC, merged