Refactor Human Resources and Payroll Management
third-culture-software/bhima pull request #7943
Opened 2024-12-21 15:16 UTC by jniles

This PR reworks the underlying Human Resources and Payroll Management procedures to allow for better code readability, maintainability, efficiency and testing.  It is part of a broader effort to rewrite the payment processes with the goal of clearly establishing and supporting multiple payroll systems in a unified way (https://github.com/Third-Culture-Software/bhima/issues/7752).

For the moment, all updates and changes are being made a feature branch `refactor-payroll-management`.  This PR pulls that branch into `master`.  It should not be merged until all work has been completed.

### Progress so far

The main improvements are the introduction of `debug()` calls, refactoring to use `async`/`await` syntax, separation of concerns into specific functions, generous use of comments, hoisting and renaming variables, and rendering loops side-effect free through functional programming.

While doing this refactor, I also tackled https://github.com/Third-Culture-Software/bhima/issues/7791, though this only applies to the `commitmentByEmployee()` function. It may be expanded later as more of the payroll code is organized.

### Payroll Concepts and Definitions

There are four basic types of payroll modifications: **benefits**, **payroll taxes**, **withholdings**, and **pension allowances**.

 -  **Benefits** are any rubrics that are paid to an employee.  In the current implementation of BHIMA payroll, the employee's base salary is classified as a benefit.  However, benefits can also be bonuses, additional compensation for family members, etc. 
     -  A benefits rubric is identified by the flag: `is_discount === 0`.
 - **Payroll Taxes** are called "charge sur remuneration" in French.  These taxes are paid by the enterprise and are not born by the employee.  
     - They are identified by the flags `is_employee !== 1`, `is_discount === 1`, `is_linked_pension_fund === 0`.  
 - **Withholdings** are monies retained/deducted by the institution from the employee's  pay.  This might be due to paying back salary advances, taking health insurance, or setting aside in an employee savings account.
     -  They are identified by `is_discount === 1` and `is_employee === 1`.
 - "**Pension Funds**" are retirement funds that are deducted from the employee salary.  
    - They are identified by `is_employee !== 0`, `is_discount === 1`, and `is_linked_pension_fund ===1`.

**Note**: we should probably rename "withholdings" to "deductions".

### Notable and/or Breaking Changes
 1. Renamed the API for `/account_config/` to `/payroll/account_config/` since it is used to configure accounts used in the payroll modules.
 2. Setting `DEBUG` to include `payroll:*` spews out much more informative information about the transaction process.
 3. The logic for determining different rubric types (e.g. taxes, pension, etc), has been moved to a `common.js` function and is shared across all commitment types.  It also has some rudimentary tests.
 4. `commitmentByEmployee()` now calls out to relevant `calculate*()` functions for taxes, withholdings, pension and benefits.  This should make the code somewhat more legible. 
 
 ### A note about testing 
We don't have vary many payroll tests.  In particular, I'm not sure we have tests for all the different types of `commitment` functions listed in the enterprise settings.  Which means that, should this get merged, we cannot be 100% this code will not break something in production.

Ideally, I'm hoping to continue to hack on payroll over the holidays until we get something that is easy to reason about, maintain, and trace if a regression or a bug occurs.  However, we probably shouldn't do a release and/or upgrade until we have better test coverage or assurance that the payroll code isn't going to break in mysterious ways at one of the production sites.
 
 ### Future Work
 This PR addresses only about a quarter of the needed payroll refactor.  In many ways, it addresses the low-hanging fruit of function signatures and variable hoisting.  More in depth refactor is needed in the following areas:
  1. Add functions to determine taxable/nontaxable income to `payroll/multiplePayroll/common.js`, document them, and test them.
  2. Apply a similar refactor seen here to files and functions in `multiplePayrollIndice` associated with multiple indexes.
  3. Apply a similar refactor to `payrollSettings` and associated files.
  5. Rework the `commitFunction#dataCommit()` function to have a simpler function signature.
  6. Document the different payroll flows in the code.
  
On thing I noticed while working on this refactor: there are several places where we loop through employees and compute rubric values that are nearly identical.  For example, each `commitment` function  (`commitment.js`, `groupedCommitment.js`, `commitmentByEmployee.js`) loops through the employees, but generates slightly different transactions with the results.  With the current code structure, this is fine.  However, there is likely a way to make some sort of intermediate representation of the data that is common between all three that we can then reuse for all three.

As an example, one can imagine some sort of pseudocode like this:

```js
const employeeRubricAssignments = loopThroughEmployeesAndComputeRubrics(employees, rubrics) 

// if groupedCommitment.js
const transaction = createGroupedVouchers(employeeRubricAssignments);

// if commitment.js
const transaction =createCommitmentVouchers(employeeRubricAssignments);

// if commitmentByEmployee.js
const transaction = createIndividualVouchers(employeeRubricAssignments);
```

An advantage of this style is that we could then write unit tests for the `loopThroughEmployeesAndComputeRubrics()` function and ensure that we are correctly expressing the rubrics as transactions.  It would make it faster and easier to write a variety of tests for different scenarios (e.g. multiple pension withholdings, increases of greater than 100%, etc).

### Unanswered Questions:

1. How are payroll taxes that are born by employees, versus those born by the institution, modeled?|

### Issues Closed

Closes #7791.

2025-02-19 21:57 UTC, jmcameron requested changes
I did a skimmy walk-through of the code changes.  There were too many to do a full evaluation.  But the changes and new code look good (as far as I could tell).

I found a translation term missing in French.

I need a better manual testing guide before completing the review.  

Please merge with the  changes in master.  I could have done this from the github API, but I thought it would be better for you to do it.

2025-02-19 21:57 UTC, jmcameron commented on client/src/i18n/en/employee.json
> +    "CREATE_ANOTHER": "Create Another"
EMPLOYEE.CREATE_ANOTHER is missing from the French translation.
See `npm run check:lang`

2025-02-19 21:57 UTC, jmcameron commented on client/src/js/services/CurrencyService.js
> +  let map;
👍

2025-02-19 21:57 UTC, jmcameron commented on client/src/modules/employees/registration/employees.html
> +      <li class="static" translate>TREE.HUMAN_RESOURCES</li>
👍

2025-02-19 21:57 UTC, jmcameron commented on client/src/modules/employees/registration/employees.html
> +                        ng-model="EmployeeCtrl.employee.hiring_date"
👍

2025-02-19 21:57 UTC, jmcameron commented on server/config/routes.js
> +  app.get('/payroll/taxes/ipr', iprTax.list);
👍

2025-02-19 21:57 UTC, jmcameron commented on server/controllers/finance/cost_center.js
> -/**
Why was this removed?

2025-02-21 23:38 UTC, jniles commented
@jmcameron thanks for your review!  I fixed up the i18n keys and `npm run check:lang` passes cleanly now.

2025-02-22 16:35 UTC, jmcameron approved these changes
My issues have been addressed.
The hands-on testing with @jniles went well.
The tests all pass locally.

2025-02-23 14:32 UTC, merged