refactor(payroll): replace "date_embauche" with"hiring_date"
third-culture-software/bhima pull request #7944
Opened 2024-12-21 15:19 UTC by jniles

Replaces the `date_embauche` with `hiring_date` for better English consistency.

Closes #7821.

2024-12-23 18:40 UTC, jmcameron requested changes
The code looks good.  
I made one minor suggestion to add a comment to the migration file.
All tests pass on my local machine.

2024-12-23 18:40 UTC, jmcameron commented on server/models/migrations/next/migrate.sql
> +
Please add a comment before this line indicating the author, date, and description. Thanks.

2024-12-24 15:42 UTC, jniles commented on server/models/migrations/next/migrate.sql
> +
Will do, thanks!

2024-12-31 13:33 UTC, jmcameron commented on server/models/migrations/next/migrate.sql
> +
Thanks

2024-12-31 13:33 UTC, jmcameron approved these changes

2024-12-31 13:33 UTC, merged