Adding footer aggrega
third-culture-software/bhima pull request #798
Opened 2016-10-11 15:26 UTC by mbayopanda

This PR add footer in the column's grid for : 
- Voucher registry 
- Patient invoices registry 
- Posting journal 
- General ledger 
- Patient registry 
- Inventory list

2016-10-11 15:44 UTC, jniles requested changes
@mbayopanda, thanks for tackling this issue so quickly.  Can you add "Closes #790" to your PR text?

You use many `footerCellFilter: currency` calls - these would be much better to use the enterprise's currency id (in case we ever support a different enterprise currency other than USD).  Could you make this change?

2016-10-11 15:44 UTC, jniles commented on client/src/i18n/fr.json
> +      "WEIGHT"                 : "Weight",
Should these be in french?

2016-10-11 15:44 UTC, jniles commented on client/src/partials/general_ledger/general_ledger.js
> +    { field : 'description', displayName : 'TABLE.COLUMNS.DESCRIPTION', headerCellFilter: 'translate', footerCellTemplate:'<i></i>' },
:dancer:

2016-10-11 15:44 UTC, jniles commented on client/src/partials/general_ledger/general_ledger.js
> +      footerCellFilter : 'currency'
This should probably have a custom cell footer so that we can use the enterprise `currency_id`.

2016-10-11 15:44 UTC, jniles commented on client/src/partials/inventory/list/list.js
> +      { field : 'groupName', displayName : 'FORM.LABELS.GROUP', headerCellFilter : 'translate'},
:+1:  Excellent improvement.

2016-10-11 15:44 UTC, jniles commented on client/src/partials/general_ledger/general_ledger.js
> +      footerCellFilter : 'currency'
Actually, I just discovered you can pass custom filter arguments to the cellFilter.  [See this plunkr](http://plnkr.co/edit/972s2MSbFDw2DtnMOmnY?p=preview).

So, you can do this:
```js
footerCellFilter: 'currency:grid.appScope.enterprise.currency_id'
```
and make sure that the enterprise is bound to the scope!

2016-10-11 21:36 UTC, mbayopanda commented
👍

2016-10-11 8:44 GMT-07:00 Jonathan Niles <notifications@github.com>:

> *@jniles* requested changes on this pull request.
>
> @mbayopanda <https://github.com/mbayopanda>, thanks for tackling this
> issue so quickly. Can you add "Closes #790
> <https://github.com/IMA-WorldHealth/bhima-2.X/issues/790>" to your PR
> text?
>
> You use many footerCellFilter: currency calls - these would be much
> better to use the enterprise's currency id (in case we ever support a
> different enterprise currency other than USD). Could you make this change?
> ------------------------------
>
> In client/src/i18n/fr.json
> <https://github.com/IMA-WorldHealth/bhima-2.X/pull/798#pullrequestreview-3700442>
> :
>
> > @@ -603,6 +603,8 @@
>        "VILLAGE"                : "Village",
>        "VILLAGE_NAME"           : "Nom du Village",
>        "VILLE"                  : "Ville/Commune",
> +      "VOLUME"                 : "Volume",
> +      "WEIGHT"                 : "Weight",
>
> Should these be in french?
> ------------------------------
>
> In client/src/partials/general_ledger/general_ledger.js
> <https://github.com/IMA-WorldHealth/bhima-2.X/pull/798#pullrequestreview-3700442>
> :
>
> >      },
> -    { field : 'description', displayName : 'TABLE.COLUMNS.DESCRIPTION', headerCellFilter: 'translate' },
> +    { field : 'description', displayName : 'TABLE.COLUMNS.DESCRIPTION', headerCellFilter: 'translate', footerCellTemplate:'<i></i>' },
>
> 💃
> ------------------------------
>
> In client/src/partials/general_ledger/general_ledger.js
> <https://github.com/IMA-WorldHealth/bhima-2.X/pull/798#pullrequestreview-3700442>
> :
>
> >      { field : 'account_number', displayName : 'TABLE.COLUMNS.ACCOUNT', headerCellFilter: 'translate' },
> -    { field : 'debit_equiv', displayName : 'TABLE.COLUMNS.DEBIT', headerCellFilter: 'translate', cellTemplate : '/partials/templates/grid/debit_equiv.cell.html' },
> -    { field : 'credit_equiv', displayName : 'TABLE.COLUMNS.CREDIT', headerCellFilter: 'translate', cellTemplate : '/partials/templates/grid/credit_equiv.cell.html' },
> +    { field : 'debit_equiv', displayName : 'TABLE.COLUMNS.DEBIT', headerCellFilter: 'translate',
> +      cellTemplate : '/partials/templates/grid/debit_equiv.cell.html',
> +      aggregationType : uiGridConstants.aggregationTypes.sum,
> +      footerCellFilter : 'currency'
>
> This should probably have a custom cell footer so that we can use the
> enterprise currency_id.
> ------------------------------
>
> In client/src/partials/inventory/list/list.js
> <https://github.com/IMA-WorldHealth/bhima-2.X/pull/798#pullrequestreview-3700442>
> :
>
> >          cellTemplate : iconTemplate
>        },
> -      { field : 'groupName', displayName : 'Groupe'},
> -      { field : 'label', displayName : 'Label'},
> -      { field : 'price', displayName : 'Price'},
> -      { field : 'type', displayName : 'Type'},
> -      { field : 'unit', displayName : 'Unit'},
> -      { field : 'unit_weight', displayName : 'Weight'},
> -      { field : 'unit_volume', displayName : 'Volume'},
> +      { field : 'groupName', displayName : 'FORM.LABELS.GROUP', headerCellFilter : 'translate'},
>
> 👍 Excellent improvement.
> ------------------------------
>
> In client/src/partials/general_ledger/general_ledger.js
> <https://github.com/IMA-WorldHealth/bhima-2.X/pull/798#pullrequestreview-3700442>
> :
>
> >      { field : 'account_number', displayName : 'TABLE.COLUMNS.ACCOUNT', headerCellFilter: 'translate' },
> -    { field : 'debit_equiv', displayName : 'TABLE.COLUMNS.DEBIT', headerCellFilter: 'translate', cellTemplate : '/partials/templates/grid/debit_equiv.cell.html' },
> -    { field : 'credit_equiv', displayName : 'TABLE.COLUMNS.CREDIT', headerCellFilter: 'translate', cellTemplate : '/partials/templates/grid/credit_equiv.cell.html' },
> +    { field : 'debit_equiv', displayName : 'TABLE.COLUMNS.DEBIT', headerCellFilter: 'translate',
> +      cellTemplate : '/partials/templates/grid/debit_equiv.cell.html',
> +      aggregationType : uiGridConstants.aggregationTypes.sum,
> +      footerCellFilter : 'currency'
>
> Actually, I just discovered you can pass custom filter arguments to the
> cellFilter. See this plunkr
> <http://plnkr.co/edit/972s2MSbFDw2DtnMOmnY?p=preview>.
>
> So, you can do this:
>
> footerCellFilter: 'currency:grid.appScope.enterprise.currency_id'
>
> and make sure that the enterprise is bound to the scope!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/IMA-WorldHealth/bhima-2.X/pull/798#pullrequestreview-3700442>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFMWg2HkzHFLXQ_Rd9kWroTFdN2FRsUmks5qy67egaJpZM4KTw9s>
> .
>

2016-10-12 09:59 UTC, jniles commented
LGTM.  :+1:

2016-10-12 10:02 UTC, merged