Debtor debt
third-culture-software/bhima pull request #844
Opened 2016-11-03 08:23 UTC by lomamech

Aged Debtor
- Adding API for Aged Debtors
- Resolve conflict with the branch Master	
- Adding test integration for AgedDebtors			
- Adding test end to end			

@sfount

2016-11-03 11:25 UTC, mbayopanda reviewed
The reports produced look very good, we just have to test it with big real data

2016-11-03 11:25 UTC, mbayopanda commented on client/src/partials/reports/modals/agedDebtors.config.js
> +
You can remove `use strict`, gulp inject it automatically

2016-11-03 11:25 UTC, mbayopanda commented on client/src/partials/reports/modals/agedDebtors.config.js
> + * all incomes minus all depenses
This description is not correct for an `Aged Report for clients`

2016-11-03 11:25 UTC, mbayopanda commented on server/config/routes.js
> -  //app.get('/reports/saved/finance/debtors/aged');
👍

2016-11-03 11:25 UTC, mbayopanda commented on server/controllers/finance/reports/agedDebtors/index.js
> + */
Very well documented 👍

2016-11-03 11:25 UTC, mbayopanda commented on server/controllers/finance/reports/agedDebtors/index.js
> +/** processingAgedDebtorsReport */
Could you give the description of this function

2016-11-03 11:25 UTC, mbayopanda commented on server/controllers/finance/reports/agedDebtors/index.js
> +  let query =`
Could you give a description for this function

2016-11-03 11:25 UTC, mbayopanda commented on server/controllers/finance/trialBalance/index.js
> +    WHERE DATE(pj.trans_date) NOT BETWEEN DATE(p.start_date) AND DATE(p.end_date) AND
👍

2016-11-04 20:00 UTC, mbayopanda commented
@lomamech could you update your branch

2016-11-07 09:00 UTC, lomamech commented
all things all Ok

@sfount @mbayopanda

2016-11-07 13:27 UTC, lomamech commented
Improve the way to get information about the kind of repots 
Update interface of modal title

I will update in the next times, the E2E test for All Reports for checked the showing of the new report in the grid

@mbayopanda

2016-11-08 10:17 UTC, mbayopanda requested changes
All things work well, excepts for extreme date `2016-12-31`. Could you try to fix it.

2016-11-08 10:17 UTC, mbayopanda commented on server/controllers/finance/reports/agedDebtors/index.js
> +
Try to use DATE function to avoid errors with limits values

2016-11-10 18:20 UTC, mbayopanda approved these changes

2016-11-10 18:21 UTC, mbayopanda commented
@lomamech could you update your branch. All things are good 👍

2016-11-10 22:18 UTC, merged