(Feature) Debtor Group -> Billing Services, Subsidy Subscriptions
third-culture-software/bhima pull request #851
Opened 2016-11-04 14:28 UTC by sfount

This pull request adds the ability to link debtor groups with billing services and subsidies. This is essential for being able to correctly bill patients according to their group assignments. 

Subscriptions are shown when managing a debtor group through the debtor group management module.

* Server controllers for listing debtor group billing services and subsidies 
* Modal for updating entity subscriptions
* Generic group subscription controller - this will be used to reduce duplicated code on the server as the number of 'subscription' relationships increases 
  * Debtor groups -> Billing services
  * Debtor groups -> Subsidies 
  * Patient groups -> Billing services 
  * Patient groups -> Subsidies 
  * Patients -> Patient groups 
* Integration tests for generic group subscription route
* End to end tests for debtor group subscription update

**Debtor Group Subscription unit**
![screenshot 2016-11-04 at 15 20 38](https://cloud.githubusercontent.com/assets/2844572/20008981/f3014caa-a2a2-11e6-948c-ec08f5c8ec6b.png)

**Update modal**
![screenshot 2016-11-04 at 15 25 11](https://cloud.githubusercontent.com/assets/2844572/20008980/f2e9d994-a2a2-11e6-95ed-70dd8b6892e1.png)

**Updated/ assigned subscriptions**
![screenshot 2016-11-04 at 15 25 30](https://cloud.githubusercontent.com/assets/2844572/20008978/f2c77c32-a2a2-11e6-8af9-aa546c25826a.png)

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull requests

2016-11-04 19:02 UTC, mbayopanda requested changes
Integration test throw errors and must be reviewed for `debtor group API` and `patient billing service`

2016-11-04 19:02 UTC, mbayopanda commented on client/src/i18n/en.json
> +    "SUBSCRIPTIONS"  : "Subscriptions"
Could you add french translations which are missing.

2016-11-04 19:02 UTC, mbayopanda commented on client/src/partials/debtors/groups.update.js
> + */
👍

2016-11-04 19:02 UTC, mbayopanda commented on client/src/partials/debtors/groups.update.js
> +  console.log('state', $state);
The `console.log` is needed ?

2016-11-04 19:02 UTC, mbayopanda commented on client/src/partials/debtors/groups.update.js
> +      console.log(vm.group);
The `console.log` must be removed.

2016-11-04 19:02 UTC, mbayopanda commented on client/src/partials/patients/edit/edit.html
> -                 <li>{{group.name}}</li>
👍

2016-11-04 19:02 UTC, mbayopanda commented on client/src/partials/patients/edit/edit.html
> +                  </li>
👍

2016-11-04 19:06 UTC, mbayopanda commented
@sfount In the debtor group management we don't have any mean to set a convention group. The ui must be updated for to have a checkbox for example to set convention or not.

2016-11-04 20:09 UTC, sfount commented
@mbayopanda thanks for the review, I'll address the tests and the debug statements. 

You are correct that convention configuration must be added to debtor groups however that has nothing to do with this work; convention's should be worked on as a separate feature request:
* Debtor groups convention specific settings 
* Journal voucher convention invoice import tool 
* Invoice/ receipt for convention current money owed

2016-11-07 09:11 UTC, sfount commented on client/src/i18n/en.json
> +    "SUBSCRIPTIONS"  : "Subscriptions"
@mbayopanda I have included the English translation keys which should give us a good idea of what we need to translate before we go for an install/ release. 

My translations would use Google Translate and I think it would be harder to track down non-nonsensical translations over ones that haven't yet been completed!

2016-11-08 12:13 UTC, mbayopanda commented
@sfount could you update this PR please

2016-11-09 14:07 UTC, mbayopanda approved these changes

2016-11-10 22:20 UTC, merged