Report accounts
third-culture-software/bhima pull request #857
Opened 2016-11-08 09:33 UTC by lomamech

Report Accounts
- Implementation of client side 
- Implementation of API and Report PDF Design
- Implementation of integration test ans E2E test

@sfount  @mbayopanda

2016-11-08 10:01 UTC, jniles requested changes
@lomamech, the code is pretty good.  I've made a few comments to improve.

For functionality, I propose you:
1. Remove the `Invoice ID`, since most accounts will never have an invoice against them.  You should remove it from the SQL as well.
2. Add an option to include the posting journal that is `false` by default.  Currently, both the General Ledger and Posting Journal is shown by default.  It should be just the General Ledger by default, with an option to enable the Posting Journal.

2016-11-08 10:01 UTC, jniles commented on client/src/i18n/fr.json
> +      "ACCOUNT"            : "Sélectionner un compte",
:+1:

2016-11-08 10:01 UTC, jniles commented on client/src/partials/reports/modals/report_accounts.config.js
> +  Accounts.read(null, { detailed: 1, is_auxiliary: 0})
You don't need `is_auxiliary` here...

2016-11-08 10:01 UTC, jniles commented on client/src/partials/reports/modals/report_accounts.config.js
> +    var url = 'reports/finance/report_accounts';
This report is for a single account, correct?  I propose that this URL should be `reports/finance/account`.

2016-11-08 10:01 UTC, jniles commented on client/src/partials/reports/modals/report_accounts.config.js
> +      account_label: vm.account.label,
Do you actually need the parameters `account_label` and `account_number`?

2016-11-08 10:01 UTC, jniles commented on server/controllers/finance/reports/reportAccounts/report.handlebars
> +{{> head title="PATIENT_RECORDS.FINANCIAL_ACTIVITY.REPORT_TITLE" }}
I think this title is wrong.

2016-11-08 10:01 UTC, jniles commented on server/controllers/finance/reports/reportAccounts/report.handlebars
> +          <th style="width: 10%;">{{translate "TABLE.COLUMNS.INVOICE_ID" }}</th>
Only class 4 accounts will have invoice IDs.  I propose you remove this column for a generic account report.

2016-11-08 15:06 UTC, lomamech commented on client/src/partials/reports/modals/report_accounts.config.js
> +      account_label: vm.account.label,
Yes, For display in the PDF report

2016-11-08 15:13 UTC, jniles commented on client/src/partials/reports/modals/report_accounts.config.js
> +      account_label: vm.account.label,
Ah, I see it now.  :+1:

2016-11-09 09:45 UTC, lomamech commented
@jniles
This branch is already for be merged

2016-11-09 10:10 UTC, jniles commented
@lomamech, I'll take a look.  Thanks!

2016-11-09 10:18 UTC, jniles commented
LGTM :+1:

2016-11-09 10:18 UTC, merged